Included many sections as tex files
rycolab/aclpub2 pull request #21
Opened 2022-02-03 16:39 UTC by marcopoli

I included meal info, venue, etc... directly as tex file

Open Issues:
- Daily Timetable for Main Conference
- Workshop program format

2022-02-06 20:00 UTC, zhzhang requested changes
Are the files in `example/handbook` able to be used with the proceedings generation script as well? If not, we will have to duplicate a lot of the files so that both can be generated. Are you able to merge the `example/handbook` with the `example/sigdial` folders so that both can be used together to represent the needs of the whole conference with one input?

2022-02-07 10:55 UTC, marcopoli commented on aclpub2/generate.py
> +
Yes, the handbook example includes the sidgial files so it is possible to compile both of them without problems.

2022-02-07 10:58 UTC, marcopoli commented on aclpub2/generate.py
> +        # Load and preprocess the .yml configuration.
Sure I Agree with you about this.

2022-02-07 14:29 UTC, marcopoli commented on aclpub2/generate.py
> +def process_program_workshop_handbook(program, max_lines = 35, paper_median_lines = 3, header_lines = 2):
It is just to keep the functions distinct in case we need to modify one of them.

2022-02-07 14:50 UTC, closed without merging